/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import type { LocaleDefinition } from '..';
import ar from './ar';
import en from './en';

export type KnownLocale = 'ar' | 'en';

export type KnownLocales = Record<KnownLocale, LocaleDefinition>;

const locales: KnownLocales = {
  ar,
  en,
};

export default locales;
